### ISSUE TITLE
error when run impatient example in IDEA

### ISSUE THREAD

**Issue by zqhxuyuan** [Cascading/Impatient#15]
My Hadoop version is hadoop-2.5.0-cdh5.2.0, It works fine When 
1. start hdfs and yarn
2. follow the tutorial use cmd: hadoop jar ./build/libs/impatient.jar data/rain.txt output/rain. 

then I try run the demo in IDEA.
I use maven project, my pom.xml like :
 <hadoop.version>2.5.0-cdh5.2.0</hadoop.version>
<cascading.version>2.6.1</cascading.version>

<dependency>
            <groupId>driven</groupId>
            <artifactId>driven-plugin</artifactId>
            <version>1.2-eap-5</version>
        </dependency>
        <dependency>
            <groupId>cascading</groupId>
            <artifactId>cascading-core</artifactId>
            <version>${cascading.version}</version>
        </dependency>
        <dependency>
            <groupId>cascading</groupId>
            <artifactId>cascading-local</artifactId>
            <version>${cascading.version}</version>
        </dependency>
        <dependency>
            <groupId>cascading</groupId>
            <artifactId>cascading-hadoop</artifactId>
            <version>${cascading.version}</version>
        </dependency>
        <dependency>
            <groupId>cascading</groupId>
            <artifactId>cascading-hadoop2-mr1</artifactId>
            <version>${cascading.version}</version>
        </dependency>
        <dependency>
            <groupId>cascading</groupId>
            <artifactId>cascading-xml</artifactId>
            <version>${cascading.version}</version>
        </dependency>
        <dependency>
            <groupId>cascading</groupId>
            <artifactId>cascading-platform</artifactId>
            <version>${cascading.version}</version>
            <scope>test</scope>
        </dependency>
then I copy Main.java, run it . Since I set inPath and outPath to local fs, I didn't start hadoop
Error happen:
---------------------------------------------------------------------------------------------------------
Exception in thread "main" cascading.flow.FlowException: unhandled exception
	at cascading.flow.BaseFlow.complete(BaseFlow.java:918)
	at com.zqh.cascading.impatient.Copy.main(Copy.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.mapred.LocalJobRunner.<init>(Lorg/apache/hadoop/conf/Configuration;)V
	at org.apache.hadoop.mapred.LocalClientProtocolProvider.create(LocalClientProtocolProvider.java:42)
	at org.apache.hadoop.mapreduce.Cluster.initialize(Cluster.java:95)
	at org.apache.hadoop.mapreduce.Cluster.<init>(Cluster.java:82)
	at org.apache.hadoop.mapreduce.Cluster.<init>(Cluster.java:75)
	at org.apache.hadoop.mapred.JobClient.init(JobClient.java:472)
	at org.apache.hadoop.mapred.JobClient.<init>(JobClient.java:450)
	at cascading.flow.hadoop.planner.HadoopFlowStepJob.internalNonBlockingStart(HadoopFlowStepJob.java:107)
	at cascading.flow.planner.FlowStepJob.blockOnJob(FlowStepJob.java:207)
	at cascading.flow.planner.FlowStepJob.start(FlowStepJob.java:150)
	at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:124)
	at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
---------------------------------------------------------------------------------------------------------
there are also errors when I start hadoop and run it .
Does this error means I use the wrong hadoop version? since my cascading-hadoop version is cascading-hadoop2-mr1. does cascading  not support mr2 or yarn?

**Comment by fs111** [comment]
Are you sure you only have one version of hadoop on your classpath?

**Comment by zqhxuyuan** [comment]
I was wrong. because I put multi bigdata-related demo into one idea module. when I catch only cascading out, It works. tks!

**Comment by fs111** [comment]
Glad you could figure it out!

**Comment by zqhxuyuan** [comment]
another solution is use exclusion on pom.xml, find conflict hadoop classpath. then you can mix multi bigdata-related demo in one idea module. today when run simple wc example, I found tez-mapreduce dependency hadoop-mapreduce-client-common was conflict with my already config. so I exclusion it. and it works. so does the same as cascading dependency.
